name: Upload SDK Package

on:
  release:
    types:
      - 'published'

defaults:
  run:
    shell: |
           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"

jobs:
  upload-sdk:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: 'Generate Release'
          workflow_conclusion: 'success'
          name: sdk

      - name: List Directory Contents
        run:  |
              ls -Recurse
  