name: Bug Report
description: File a bug report
title: "[BUG] "
labels: [ "bug", "triage" ]
assignees:
  - radj307
body:
  - type: markdown
    attributes:
      value: |
             Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of Volume Control the bug occurred in. You can find this on the settings tab in the top-right corner. If you are unable to access the application, R+Click on the executable, click Properties, and find the version number on the details tab.
      placeholder: Version Number found in the top-right corner of the settings tab.
    validations:
      required: true
      
  - type: checkboxes
    id: version-is-extended
    attributes:
      label:        
      description:  This is especially relevant when considering the version number field.
      options:
        - label: Can you launch the program?
          required: false
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      placeholder: What did you expect to happen, and if relevant, why?
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened? Be specific
      placeholder: What actually happened?
    validations:
      required: true
        
  - type: textarea
    id: logs
    attributes:
      label: Log File Contents
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
