name: Bug Report
description: File a bug report
title: "[BUG] "
labels: [ "bug", "triage" ]
body:
  - type: markdown
    attributes:
      value:  |
              Thank you for taking the time to fill out a bug report, your feedback helps us to improve your experience with our product!  
              
              The more fields you can fill out, the better our understanding of the problem and its underlying causes.  
              If you feel a section doesn't apply or is already obvious from previous fields, skip them.
              
  - type: input
    id: version
    attributes:
      label: Version
      description:  |
                    This tells us what version of the program we need to fix, and can be found to the left of the minimize & close buttons on the top bar.
                    If the program won't start, R+Click on the executable and click ***Properties** -> **Details***; copy the `Product version` field.
      placeholder: x.x.x
    validations:
      required: true

  - type: textarea
    id:   actual
    attributes:
      label:        Actual Behaviour
      description:  |
                    This tells us what happened, which helps us build a description of the bug we need to fix.
                    Please be specific whenever possible.
      placeholder:  The program does *this*
    validations:
      required: true

  - type: textarea
    id:   expected
    attributes:
      label:        Expected Behaviour
      description:  |
                    This gives us an idea of what we should do to fix the problem, and/or provides you with a way to suggest what you want to happen.
      placeholder:  I expected the program to do *that*

  - type: textarea
    id:   repro
    attributes:
      label:        Reproduction Steps
      description:  |
                    This helps us replicate the conditions that led to the bug you experienced while running in a different environment.
                    While this is optional, it is highly encouraged since it cuts the amount of time needed to fix the problem by half in most cases.
                    
                    You can optionally combine this with the log field below and use specific log events as reproduction steps instead of specifying both.
      placeholder:  |
                    1. While sitting in an office chair, begin spinning clockwise as fast as you can until you've fully rotated a total of 99 times.
                    2. Launch the program within a few seconds.
                    3. Observe vomit on screen instead of application window.

  - type: textarea
    id:   log
    attributes:
      label:        Log
      description:  |
                    This gives us an understanding of exactly what was happening when the problem occurred.
                    
                    **Discretion is advised when posting raw log contents, especially when the `DEBUG` or `INFO` log filters are enabled, as there may be references to potentially sensitive information like filepaths & audio device/session names.**  
      render:       shell
