name:         'Compatibility Report'
description:  'Provide Operating System Support Feedback'
title:        'Windows Version Compatibility Report'
labels:       ['os-support']
assignees:
  - radj307
body:
  - type: markdown
    attributes:
      value:  |
              Thanks for taking the time to fill out a compatibility report!  
              Your contribution lets us know how to improve Volume Control by improving compatibility with your version of Windows.
              
              
  - type: dropdown
    id:   version
    attributes:
      label:  Which Windows Version are you reporting?
      description: Only unconfirmed versions of Windows are listed here.
      options:
        - Windows Vista
        - Windows 7
        - Windows 8
        - Windows 8.1
        - Windows 11      
  - type: dropdown
    id:   state
    attributes:
      label:        Support Status
      description:  Select the option that best describes the current level of support for your OS.
      options:
        - Fully Compatible  (No Perceivable Issues)
        - Mostly Compatible (Minor Issues; Hotkeys and UI are functional)
        - Barely Compatible (Major Issues; Essential features are non-functional)
        - Not Compatible    (Cannot launch Volume Control, or it is entirely non-functional)
  - type: markdown
    attributes:
      value:  |
              If you selected the ***Fully Compatible*** option above, you can skip the rest of the form.  
              If you selected any other options, please fill in the rest of the form.
  - type: textarea
    id:   log
    attributes:
      label:       Log
      description: Please attach a copy of the log file.
      placeholder: By default, the log file is named `volumecontrol.log` and is located in the same directory as the executable.
  - type: textarea
    id:   details
    attributes:
      label:        Additional Details (Optional)
      description:  If you have any other information to provide, you can do so here.  
      placeholder:  Descriptions and/or images of the problem.
