name: Format Code

on:
## Waiting until a prettier plugin for C# is available.
## https://github.com/warrenseine/prettier-plugin-csharp
#  push:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref:  ${{ github.head_ref }}
          fetch-depth:  0
          
      - name: Prettify Code
        uses: creyD/prettier_action@v4.2
        with:
          github_token: ${{ secrets.PAT }}
          prettier_options: --write **/*.cs
          #prettier_plugins: 
          same_commit:  true
          only_changed: true
      
