name: Publish to Winget

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: radj307.volume-control
          version: ${{ github.event.release.tag_name }}
          installers-regex: '-Installer\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
