name: Publish to Winget

on:
  release:
    types: [released]
  workflow_dispatch:

defaults:
  run:
    shell:  |
            pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
               
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - run:  |
              ${{ github.event.release.tag_name }}

      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: radj307.volume-control
          version: ${{ github.event.release.tag_name }}
          installers-regex: '-Installer\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
